### ISSUE TITLE
what is license of this project

### ISSUE THREAD

**Issue by ojczeo** [ReneCode/sketch-vue#2]
Is it released on MIT license?

**Comment by ReneCode** [comment]
hi, 
currently that is only a "try-out" project. I've not thought about the license yet.
Do you want to contribute ?
That would be fine.

**Comment by ojczeo** [comment]
I would like to use few [canvas] components in commercial project. What do
you think?

pt., 15.12.2017, 19:19 użytkownik Rene <notifications@github.com> napisał:

**Comment by ReneCode** [comment]
yes you can use the code. 👍 
I'm proud to see someone can use my code.
/
Where do I have to set the license? package.json?

**Comment by ojczeo** [comment]
👍 👍 👍  Thank you! :)
About license check this article:
https://help.github.com/articles/adding-a-license-to-a-repository/
and this:
https://help.github.com/articles/licensing-a-repository/
